image: node:16

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - cp -r build dist/
    - npm run build
  artifacts:
    paths:
      - dist/  # The 'dist' folder is the standard output for Vite builds
    expire_in: 1 week

deploy:
  stage: deploy
  image: alpine:latest # Use a smaller image for deployment
  before_script:
    - apk add --no-cache rsync  # Install rsync for efficient file transfer
  script:
    - rsync -avz dist/ /var/www/html/1st/ # Deploy to correct path
  only:
    - master